modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/Pbone3/SimplyCoins/issues"
license = "MIT"

[[mods]]
modId = "simplycoins"
version = "${version}"
displayName = "Simply Coins"
authors = "pbone"
description = '''
Adds coins.
'''
#logoFile = ""

[[dependencies.examplemod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"